### ISSUE TITLE
Scan for matches

### ISSUE THREAD

**Issue by hfx541** [BiCroLab/blissNP#4]
Hello,

I am trying to utilize your script for my set of data files I generated according to your protocol published in Nature protocols. I was able to run and complete the script on the test dataset you had provided here. However, I fail to process my fastq files and the issue seems to be linked to scan for matches portion of the job. I am pasting the error output I am receiving when running the script. Scanformatches fails to filter any reads based on UMI+SB, therefore not able to align any reads. Do you have any suggestions on what could be wrong here, as I find it strange that it works fine on the test dataset. 

Many thanks for your help.

Filip
[output1.txt](https://github.com/BiCroLab/blissNP/files/7333125/output1.txt)
[output2.txt](https://github.com/BiCroLab/blissNP/files/7333126/output2.txt)

**Comment by Adnanhashim** [comment]
Hi,
have you resolved this issue ?

**Comment by santoshbiowarrior333** [comment]
Scan for matches command not found. Any luck?
